.TH NAME
.PP
piglatin \- A toy CLI piglatin translator
.TH SYNOPSIS
.nf
> piglatin
this is some text
C^D
isthay isay omesay exttay
> cat sometext.txt | piglatin
.fi
.TH DESCRIPTION
.PP
Takes text from standard input and translates it into Pig Latin.
(see 
.UR http://en.wikipedia.org/wiki/Pig_Latin
.UE )
.TH AUTHOR
.PP
Delon Newman 
.MT delon.newman@gmail.com
.ME
